### ISSUE TITLE
Add PHPDoc

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/app-tutorial#4]
e.g. https://github.com/owncloud/app-tutorial/blob/master/db/note.php#L10

**Comment by BernhardPosselt** [comment]
What kind of phpdoc?

**Comment by DeepDiver1975** [comment]
like declaring types on fields etc

**Comment by BernhardPosselt** [comment]
Not needed since this is usually done with $this->addType() :) so all the values are strings. Looking at the database.xml you can also figure out what types there are
