### ISSUE TITLE
Handlrbars is already in core - no need to ship it from my pov ???

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/app-tutorial#5]
https://github.com/owncloud/app-tutorial/blob/master/js/handlebars.js

**Comment by BernhardPosselt** [comment]
It is better to not depend on anything except jquery because you guys go on regular js lib removal frenzies ;D 

You can also update it how you like it, you can use an older/newer version which is not possible by depending on the core version. So I think it is best practice to do it like this.

**Comment by DeepDiver1975** [comment]
fair enough :speak_no_evil:
